### PR TITLE
new file:   backend/examples/crabfeeder.rs

### PR DESCRIPTION
**Pull request by stappersg**
a SMTP client for injecting emails into mailcrab

### CODE REVIEW

**Comment by stappersg** [comment]
Marked as _Work In Progress_ because the actual sending has still to be implemented.
Reason for the _early release_ is preventing _code duplication_.

**Comment by stappersg** [comment]
The `examples/crabfeeder.rs` considered complete.  ( Label _WIP_ removed. )

This _merge request_ also brings in `examples/multiple_rcpt_to.rs` (https://github.com/tweedegolf/mailcrab/pull/82/commits/c342fc9c726656da713bb909a7f3e9235e06cc70).

**Comment by stappersg** [comment]
cross reference to #69

**Comment by marlonbaeten** [comment]
We already have e mechanism for sending test messages, as a Rust test case - see `https://github.com/tweedegolf/mailcrab/blob/main/backend/src/main.rs#L303`
This will send all files in the `samples/` directory as an email, interpreting the first two lines as sender en recipient addresses respectively.

**Pull request closed without merging**
